use harsh_data;

select * from [dbo].[Club24];

select * from [dbo].[Club24]
where SCRIP_SYMBOL like 'BANKNIFT 27Feb25%';

select * from [dbo].[Club2]
where SCRIP_SYMBOL like 'FINNIFTY 28Jan25%';

UPDATE [dbo].[Club24]
SET SCRIP_SYMBOL = REPLACE(SCRIP_SYMBOL, '26Feb25', '27Feb25')
WHERE SCRIP_SYMBOL LIKE 'BANKNIFT 26Feb25%';

UPDATE Club2
SET SCRIP_SYMBOL = REPLACE(SCRIP_SYMBOL, '28Jan25', '30Jan25')
WHERE SCRIP_SYMBOL LIKE 'FINNIFTY 28Jan25%';

UPDATE Club2
SET SCRIP_SYMBOL = REPLACE(SCRIP_SYMBOL, '27Jan25', '30Jan25')
WHERE SCRIP_SYMBOL LIKE 'MIDCPNIF 27Jan25%';

UPDATE Club2
SET SCRIP_SYMBOL = REPLACE(SCRIP_SYMBOL, '27Jan25', '28Jan25')
WHERE SCRIP_SYMBOL LIKE 'BANKEX 27Jan25%';

select * from [dbo].[Club2]
where TradeDate like '%2025%';

SELECT 
    REPLACE(SCRIP_SYMBOL, '29Jan25', '30Jan25') AS Updated_SCRIP_SYMBOL
FROM Club2
WHERE SCRIP_SYMBOL LIKE 'BANKNIFT 29Jan25%';



