USE [2526 EXPOPT]
GO
/* 
delete from [dbo].[StroedData]
where ExchangeTradeTime like '%20250403%'
delete from [dbo].[StroedData]
where ExchangeTradeTime like '%20250407%'
*/


INSERT INTO [dbo].[StroedData]
           ([Server]
           ,[UserID]
           ,[MAINTradeID]
           ,[MAINOrderID]
           ,[OrderID]
           ,[ExchangeOrderNo]
           ,[ExchangeTradeID]
           ,[OrderTime]
           ,[ExchangeOrderTime]
           ,[ExchangeTradeTime]
           ,[Exchange]
           ,[SecurityID]
           ,[Symbol]
           ,[ExpiryDate]
           ,[SecurityType]
           ,[Side]
           ,[OrderType]
           ,[Quantity]
           ,[PendingQuantity]
           ,[Price]
           ,[StrikePrice]
           ,[ClientID]
           ,[ReferenceText]
           ,[CTCLID]
           ,[MemberID]
           ,[StrategyID]
           ,[OptionType]
           ,[OpenClose]
           ,[ProductType]
           ,[ManagerID]
           ,[Pancard]
           ,[TerminalInfo]
           ,[AlgoID]
           ,[AlgoCategory]
           ,[ParticipantID]
		   ,[Multiplier]
           ,[DataDate])
     select
           [Server]
           ,[UserID]
           ,[MAINTradeID]
           ,[MAINOrderID]
           ,[OrderID]
           ,[ExchangeOrderNo]
           ,[ExchangeTradeID]
           ,[OrderTime]
           ,[ExchangeOrderTime]
           ,[ExchangeTradeTime]
           ,[Exchange]
           ,[SecurityID]
           ,[Symbol]
           ,[ExpiryDate]
           ,[SecurityType]
           ,[Side]
           ,[OrderType]
           ,[Quantity]
           ,[PendingQuantity]
           ,[Price]
           ,[StrikePrice]
           ,[ClientID]
           ,[ReferenceText]
           ,[CTCLID]
           ,[MemberID]
           ,[StrategyID]
           ,[OptionType]
           ,[OpenClose]
           ,[ProductType]
           ,[ManagerID]
           ,[Pancard]
           ,[TerminalInfo]
           ,[AlgoID]
           ,[AlgoCategory]
           ,[ParticipantID]
           ,[Multiplier]
		   ,upper(FORMAT(GETDATE(), 'ddMMMyyyy'))
		from UpData

GO