use harsh_data;

UPDATE Club19
SET TradeDate = FORMAT(CAST(TradeDate AS DATE), 'MM/dd/yyyy');


SELECT * FROM Club19
WHERE CLIENT_ID = 'EXPOPT96'
AND TradeDate = '03/13/2025'
AND COMPANY_CODE = 'EXPENSES'
AND SCRIP_SYMBOL = '*VIRTUAL Dr*';


DELETE FROM Club19
WHERE CLIENT_ID = 'EXPOPT96'
AND TradeDate = '03/13/2025'
AND COMPANY_CODE = 'EXPENSES'
AND SCRIP_SYMBOL = '*VIRTUAL Dr*';