use harsh_data;

select * from [dbo].[Club10];

SELECT * 
FROM Club10
WHERE CLIENT_ID LIKE 'EXPOPT%' 
AND CAST(SUBSTRING(CLIENT_ID, 7, LEN(CLIENT_ID) - 6) AS INT) BETWEEN 101 AND 138
ORDER BY CLIENT_ID;

